//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fish
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<double> length { get; set; }
        public string species { get; set; }
        public Nullable<System.DateTime> caughtDate { get; set; }
        public Nullable<int> tripId { get; set; }
        public string notes { get; set; }
        public Nullable<System.TimeSpan> caughtTime { get; set; }
        public Nullable<double> girth { get; set; }
        public string spot { get; set; }
        public string presentation { get; set; }
        public Nullable<double> depth { get; set; }
        public Nullable<double> clarity { get; set; }
        public Nullable<double> temperature { get; set; }
    
        public virtual Species Species1 { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
